---
title: "Quarto test"
format: 
  html:
    page-layout: custom
server: shiny
---

## Eksempel

Dette er et eksempel på bruk av Quarto (<https://quarto.org>).

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
#| output: false

library(tidyverse)
library(knitr)
#library(DT)
library(reactable)

df <- read_csv2("data/07459_20240201-095258.csv")

df <- 
  df |> 
  mutate(
    region = iconv(region, "latin1", "utf-8"),
    alder = as.numeric(str_replace(alder," .*$", "")),
    kommnr = str_replace(region, " .*$", ""),
    kommnavn = str_replace(region, ".*? ", "")
  ) |> 
  rename(n = Persone)

average <-
  df |> 
  mutate(
    age_sum = n * alder,
  ) |> 
  group_by(kommnr, kommnavn, kjonn) |> 
  mutate(
    age_mean = round(sum(age_sum)/sum(n),1),
  ) |> 
  distinct(age_mean)



```


````{r}
#| panel: sidebar

selectInput('komm', 'Kommune', unique(df$kommnr))

```

````{r}
#| panel: fill

tableOutput("tbl")

```


```{r}
#| context: server
selectedData <- reactive({
    average |> 
      filter(kommnr == input$komm) 
  })

output$tbl <- renderTable({
  selectedData()
  
  })


```
